In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt,exp
from sklearn import metrics
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn import preprocessing
from scipy import stats

In [2]:
samp=pd.read_csv("working_csv.csv")
samp

P. Name P. Zone Class P. Mass Class P. Composition Class  \
0              GJ 163 c          Warm   Superterran           rocky-iron   
1            GJ 667 C e          Warm        Terran           rocky-iron   
2            GJ 667 C f          Warm        Terran           rocky-iron   
3              GJ 682 c          Warm   Superterran           rocky-iron   
4             GJ 3293 d          Warm   Superterran           rocky-iron   
5            HD 40307 g          Warm   Superterran           rocky-iron   
6             Kapteyn b          Warm        Terran           rocky-iron   
7           Kepler-62 f          Warm        Terran           rocky-iron   
8          Kepler-150 f          Warm   Superterran                  gas   
9          Kepler-174 d          Warm   Superterran           rocky-iron   
10         Kepler-296 f          Warm   Superterran           rocky-iron   
11         Kepler-442 b          Warm        Terran           rocky-iron   
12        Kepler-1229 b          Warm        Terran           rocky-iron   
13        Kepler-1652 b          Warm        Terran           rocky-iron   
14           LHS 1140 b          Warm        Terran           rocky-iron   
15        Proxima Cen b          Warm        Terran           rocky-iron   
16         TRAPPIST-1 e          Warm        Terran           rocky-iron   
17         TRAPPIST-1 f          Warm        Terran          rocky-water   
18        Kepler-1410 b          Warm   Superterran           rocky-iron   
19        Kepler-1544 b          Warm   Superterran           rocky-iron   
20         Kepler-705 b          Warm   Superterran           rocky-iron   
21         Kepler-438 b          Warm        Terran           rocky-iron   
22             GJ 832 c          Warm   Superterran           rocky-iron   
23             GJ 180 b          Warm   Superterran           rocky-iron   
24           GJ 667 C c          Warm        Terran           rocky-iron   
25         Kepler-440 b          Warm   Superterran           rocky-iron   
26         Kepler-452 b          Warm   Superterran           rocky-iron   
27         Kepler-296 e          Warm        Terran           rocky-iron   
28         Kepler-283 c          Warm   Superterran           rocky-iron   
29          Kepler-61 b          Warm   Superterran           rocky-iron   
30         TRAPPIST-1 d          Warm     Subterran           rocky-iron   
31          Kepler-22 b          Warm   Superterran           rocky-iron   
32           Ross 128 b          Warm        Terran           rocky-iron   
33              K2-72 e          Warm        Terran           rocky-iron   
34             GJ 422 b          Warm   Superterran           rocky-iron   
35            tau Cet e          Warm        Terran           rocky-iron   
36         Kepler-957 b           Hot     Neptunian                  gas   
37        HD 132563 B b          Cold        Jovian                  gas   
38         Kepler-323 c           Hot   Superterran           rocky-iron   
39         Kepler-311 b           Hot   Superterran           rocky-iron   
40            WASP-41 b           Hot        Jovian                  gas   
41         Kepler-193 b           Hot   Superterran           rocky-iron   
42            HD 3167 d           Hot   Superterran           rocky-iron   
43           beta Cnc b           Hot        Jovian                  gas   
44           HD 30177 b          Cold        Jovian                  gas   
45        Kepler-1482 b           Hot        Terran           rocky-iron   
46          HD 204313 c           Hot     Neptunian                  gas   
47        Kepler-1277 b           Hot   Superterran           rocky-iron   
48  MOA-2008-BLG-310L b          Cold        Jovian                  gas   
49         Kepler-677 b           Hot     Neptunian                  gas   
50        Kepler-1454 b           Hot   Superterran           rocky-iron   
51        Kepler-1189 b           Hot   Superterran           ro

In [4]:
target_column="P. Habitable Class"
categorical_df1 = pd.DataFrame()
d_types = list(samp.dtypes)
cols = list(samp.columns)
for i,j in zip(cols,d_types):
    if j == "object":
        categorical_df1[i] = samp[i]
categorical_df1

P. Name P. Zone Class P. Mass Class P. Composition Class  \
0              GJ 163 c          Warm   Superterran           rocky-iron   
1            GJ 667 C e          Warm        Terran           rocky-iron   
2            GJ 667 C f          Warm        Terran           rocky-iron   
3              GJ 682 c          Warm   Superterran           rocky-iron   
4             GJ 3293 d          Warm   Superterran           rocky-iron   
5            HD 40307 g          Warm   Superterran           rocky-iron   
6             Kapteyn b          Warm        Terran           rocky-iron   
7           Kepler-62 f          Warm        Terran           rocky-iron   
8          Kepler-150 f          Warm   Superterran                  gas   
9          Kepler-174 d          Warm   Superterran           rocky-iron   
10         Kepler-296 f          Warm   Superterran           rocky-iron   
11         Kepler-442 b          Warm        Terran           rocky-iron   
12        Kepler-1229 b          Warm        Terran           rocky-iron   
13        Kepler-1652 b          Warm        Terran           rocky-iron   
14           LHS 1140 b          Warm        Terran           rocky-iron   
15        Proxima Cen b          Warm        Terran           rocky-iron   
16         TRAPPIST-1 e          Warm        Terran           rocky-iron   
17         TRAPPIST-1 f          Warm        Terran          rocky-water   
18        Kepler-1410 b          Warm   Superterran           rocky-iron   
19        Kepler-1544 b          Warm   Superterran           rocky-iron   
20         Kepler-705 b          Warm   Superterran           rocky-iron   
21         Kepler-438 b          Warm        Terran           rocky-iron   
22             GJ 832 c          Warm   Superterran           rocky-iron   
23             GJ 180 b          Warm   Superterran           rocky-iron   
24           GJ 667 C c          Warm        Terran           rocky-iron   
25         Kepler-440 b          Warm   Superterran           rocky-iron   
26         Kepler-452 b          Warm   Superterran           rocky-iron   
27         Kepler-296 e          Warm        Terran           rocky-iron   
28         Kepler-283 c          Warm   Superterran           rocky-iron   
29          Kepler-61 b          Warm   Superterran           rocky-iron   
30         TRAPPIST-1 d          Warm     Subterran           rocky-iron   
31          Kepler-22 b          Warm   Superterran           rocky-iron   
32           Ross 128 b          Warm        Terran           rocky-iron   
33              K2-72 e          Warm        Terran           rocky-iron   
34             GJ 422 b          Warm   Superterran           rocky-iron   
35            tau Cet e          Warm        Terran           rocky-iron   
36         Kepler-957 b           Hot     Neptunian                  gas   
37        HD 132563 B b          Cold        Jovian                  gas   
38         Kepler-323 c           Hot   Superterran           rocky-iron   
39         Kepler-311 b           Hot   Superterran           rocky-iron   
40            WASP-41 b           Hot        Jovian                  gas   
41         Kepler-193 b           Hot   Superterran           rocky-iron   
42            HD 3167 d           Hot   Superterran           rocky-iron   
43           beta Cnc b           Hot        Jovian                  gas   
44           HD 30177 b          Cold        Jovian                  gas   
45        Kepler-1482 b           Hot        Terran           rocky-iron   
46          HD 204313 c           Hot     Neptunian                  gas   
47        Kepler-1277 b           Hot   Superterran           rocky-iron   
48  MOA-2008-BLG-310L b          Cold        Jovian                  gas   
49         Kepler-677 b           Hot     Neptunian                  gas   
50        Kepler-1454 b           Hot   Superterran           rocky-iron   
51        Kepler-1189 b           Hot   Superterran           ro

In [14]:
samp1=samp.drop(columns=list((categorical_df1.drop(columns=target_column)).columns))
samp1[target_column] = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
samp1

P. Density (EU)  P. Gravity (EU)  P. Esc Vel (EU)  P. SFlux Min (EU)  \
0              1.19             2.17             1.99           0.551557   
1              0.99             1.39             1.39           0.290249   
2              0.99             1.39             1.39           0.530653   
3              1.24             2.37             2.13           0.302060   
4              1.20             2.22             2.03           0.447687   
5              1.18             2.15             1.98           0.389528   
6              1.09             1.79             1.71           0.290059   
7              1.00             1.41             1.41           0.388223   
8              0.19             0.68             1.57           0.492721   
9              1.42             3.10             2.60           0.426752   
10             1.15             2.01             1.87           0.268783   
11             0.97             1.30             1.32           0.646680   
12             0.99             1.39             1.40           0.490155   
13             0.90             1.01             1.06           0.650472   
14             2.26             3.23             2.15           0.234181   
15             0.90             1.01             1.07           0.656212   
16             0.82             0.76             0.83           0.654408   
17             0.59             0.61             0.80           0.377289   
18             1.16             2.07             1.92           1.344376   
19             1.16             2.07             1.92           0.902173   
20             1.36             2.86             2.46           0.832599   
21             0.90             1.01             1.06           1.298292   
22             1.12             1.89             1.79           0.931509   
23             1.22             2.32             2.09           0.996019   
24             1.05             1.61             1.57           0.842772   
25             1.20             2.24             2.04           0.751446   
26             1.09             1.77             1.70           1.109832   
27             1.03             1.52             1.50           1.005184   
28             1.18             2.14             1.97           0.898436   
29             1.39             2.99             2.54           0.788534   
30             0.90             0.69             0.73           1.129725   
31             1.57             3.68             2.94           1.106029   
32             0.91             1.05             1.10           1.176261   
33             0.99             1.39             1.40           1.461332   
34             1.28             2.53             2.24           0.616431   
35             1.07             1.70             1.64           1.369828   
36             0.20             1.09             2.45          86.188740   
37             0.36             3.98             6.59           0.101869   
38             1.09             1.76             1.69         758.534200   
39             1.12             1.91             1.80         204.091400   
40             0.13             1.71             4.76         479.418800   
41             1.60             3.81             3.02         170.082700   
42             1.17             2.12             1.96          45.869850   
43             1.57            18.26            14.59         161.715400   
44             1.62            18.92            14.84           0.061150   
45             0.87             0.88             0.94          53.439640   
46             0.20             0.89             1.99          21.177590   
47             1.08             1.72             1.66          14.230180   
48             0.20             1.45             3.21           0.128967   
49             0.20             1.07             2.40         200.023200   
50             1.22             2.29             2.08           9.648586   
51             1.16             2.05             1.9

In [162]:
def mean_variance(x,y):
    no_of_attributes = x.shape[1]
    mean = np.zeros((no_of_attributes,3))
    variance = np.zeros((no_of_attributes,3))
    for i in range(no_of_attributes):
        count = [0,0,0]
        sums = [0,0,0]
        for j in range(len(y)):
            if y[j] == 0:
                count[0]+=1
                sums[0]=sums[0]+x[j][i]
            elif y[j] == 1:
                count[1]+=1
                sums[1]=sums[1]+x[j][i]
            elif y[j] == 2 :
                count[2]+=1
                sums[2]=sums[2]+x[j][i]
        mean[i]=[sums[0]/count[0] , sums[1]/count[1], sums[2]/count[2] ]
        sums = [0,0,0]
        for j in y:
            if j == 0:
                sums[0]+=pow((j-mean[i][0]),2)
            if j == 1:
                sums[1]+=pow((j-mean[i][1]),2)
            if j == 2:
                sums[2]+=pow((j-mean[i][2]),2)
        variance[i] = [sums[0]/(count[0]-1), sums[1]/(count[1]-1), sums[2]/(count[2]-1)]
    print("MEAN : shape = ",mean.shape)
    print(mean)
    print("VARIANCE : shape = ",variance.shape)
    print(variance)
    return mean,variance

In [75]:
def prior_prob(y):
    d={}
    for i in y:
        if i in d:
            d[i]+=1
        else:
            d[i]=1
    prior_probabilities = [(d[0]/len(y)),(d[1]/len(y)),(d[2]/len(y))]
    print("PRIOR_PROBABILITIES: ",prior_probabilities)
    return prior_probabilities

In [149]:
def posterior_prob_per_class(mean,variance,test_val):
    pxc = [1,1,1]
#     for i in range(3):
#         for j in range(mean.shape[0]):
#             pxc[i] = pxc[i]*(1/sqrt(2*3.14*variance[j][i]))*exp(-0.5*(pow((test_val[j]-mean[j][i]),2))/(variance[j][i]))
    for i in range(0, 3):
        product = 1
        for j in range(0, mean.shape[0]):
            product = product * (1/sqrt(2*3.14*variance[j][i])) * exp(-0.5 * pow((test_val[j] - mean[j][i]),2)/variance[j][i])
        pxc[i] = product
    pxc = np.array(pxc)
    print("test data : ",test_val)
    print("Posterior Probabilities : ",pxc)
    return pxc

In [154]:
def GNBpredict(X_train,Y_train,X_test):
    mean,variance = mean_variance(X_train,Y_train)
    prior_probabilities = prior_prob(Y_train)
    Y_pred=[]
    Y_pred_prob=[]
    for i in X_test:
        pcx = [1,1,1]
        prob = [1,1,1]
        posterior_probabilities = posterior_prob_per_class(mean,variance,i)
        total = 0
        for i in range(3):
            pcx[i] = prior_probabilities[i]*posterior_probabilities[i]
            total = total + pcx[i]
        print("Prior * Posterior : ",pcx)
        for i in range(3):
            prob[i] = pcx[i]/total
        prob = np.array(prob)
        print("Probabilities ",prob)
        prediction = int(prob.argmax())
        print("Prediction ",prediction)
        Y_pred.append(prediction)
    Y_pred = np.array(Y_pred)
    return Y_pred

In [106]:
def generate_model_metrics(y_test,y_pred):
    x={"conf_matrix":metrics.confusion_matrix(y_test, y_pred),"Accuracy":metrics.accuracy_score(y_test,y_pred),"Precision":metrics.precision_score(y_test, y_pred, average="micro"),"Recall":metrics.recall_score(y_test, y_pred,average="micro"),"F1_Score":metrics.f1_score(y_test,y_pred,average="micro")}
    print("Confusion Matrix : \n",x["conf_matrix"])
    print("Accuracy of classifier : ",x["Accuracy"])
    print("Precision of classifier : ",x["Precision"])
    print("Sensitivity/Recall/TruePositiveRate of classifier : ",x["Recall"])
    print("F1 Score of classifier : ",x["F1_Score"])

In [138]:
Y = samp1[target_column]
X = samp1.drop(columns=target_column)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30)
X_train = stats.zscore(X_train, axis=1, ddof=1)
X_test = stats.zscore(X_test, axis=1, ddof=1)
X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)

In [163]:
Y_pred = GNBpredict(X_train, Y_train, X_train)
print("Confusion Matrix : \n",metrics.confusion_matrix(Y_train, Y_pred))
print("Classification Report : \n",metrics.classification_report(Y_train, Y_pred))
generate_model_metrics(Y_train, Y_pred)
print("Y_test : ",Y_train)
print("Y_pred : ",Y_pred)

MEAN : shape =  (35, 3)
[[-0.18631114 -0.18854984 -0.23540499]
 [-0.18535341 -0.18756878 -0.2309498 ]
 [-0.18553657 -0.18772977 -0.23138572]
 [-0.18735143 -0.18856158  0.12969082]
 [-0.18725145 -0.18848541  0.13713423]
 [-0.1870741  -0.18839594  0.15180032]
 [ 0.17846373  0.21460606  0.55448893]
 [-0.21626326 -0.21793437 -0.26023995]
 [-0.18324894 -0.18575586 -0.22645199]
 [-0.18798519 -0.19017848 -0.2363532 ]
 [-0.18768191 -0.189789   -0.23556264]
 [-0.08962656 -0.07054876 -0.19739431]
 [-0.18753078 -0.18943957 -0.23535432]
 [ 5.72047909  5.72264362  5.2967176 ]
 [-0.18850083 -0.19041745 -0.23648667]
 [-0.18226173 -0.18420302 -0.23217114]
 [-0.16772089 -0.1714712  -0.22485206]
 [ 0.03034267  0.00732105  0.50081883]
 [-0.16477413 -0.16233042 -0.22163048]
 [-0.20583302 -0.18442604 -0.21316258]
 [-0.2303858  -0.23125415 -0.26719093]
 [-0.18631044 -0.18797967 -0.22863721]
 [-0.18325661 -0.18512442 -0.23490594]
 [-0.18568192 -0.18767598 -0.23642975]
 [-0.18749995 -0.18934124 -0.22905879]
 

C:\Users\adith\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [140]:
Y_train

array([0, 0, 0, 1, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 0, 2, 2, 2, 0, 1, 1, 0,
       1, 2, 2, 2, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 2], dtype=int64)

In [141]:
X_train[35]

array([-0.18182841, -0.18051715, -0.18068745, -0.18214939, -0.18205208,
       -0.18194713,  0.25544872, -0.21491624, -0.17826929, -0.1836846 ,
       -0.18346321, -0.04750167, -0.18296937,  5.72882057, -0.18426359,
       -0.17660935, -0.16892023, -0.17532323, -0.14702164, -0.26719417,
       -0.22920379, -0.18123596, -0.18032983, -0.18203276, -0.18315328,
       -0.18494476, -0.18399112, -0.1829864 , -0.1828161 , -0.18206682,
       -0.18235631, -0.18203276, -0.18203276, -0.18373568, -0.18203276])

In [142]:
Y_test

array([0, 2, 0, 1, 1, 2, 2, 2, 1, 0, 1, 2, 1, 1, 0, 0, 2], dtype=int64)

In [143]:
X_test

array([[-1.90650629e-01, -1.89225672e-01, -1.89457642e-01,
        -1.92110742e-01, -1.91993438e-01, -1.91834774e-01,
         1.50262199e-01, -2.21088387e-01, -1.87038527e-01,
        -1.92357265e-01, -1.92092156e-01, -1.92556096e-01,
        -1.91810479e-01,  5.72598884e+00, -1.92754927e-01,
        -1.85597001e-01, -1.75821128e-01,  1.81909513e-01,
        -1.60904307e-01, -1.10642075e-01, -2.34973439e-01,
        -1.91204872e-01, -1.84271459e-01, -1.89242241e-01,
        -1.91981142e-01, -1.91893325e-01, -1.92788066e-01,
        -1.91131138e-01, -1.91711063e-01, -1.92556096e-01,
        -1.91561939e-01, -1.92556096e-01, -1.90899168e-01,
        -1.92556096e-01, -1.90899168e-01],
       [-2.78209082e-01, -2.77354671e-01, -2.77498673e-01,
         3.45304543e-01,  3.45304639e-01,  3.45304735e-01,
         9.55925772e-01, -3.03793423e-01, -2.76097054e-01,
        -2.79322697e-01, -2.79274697e-01, -2.79322697e-01,
        -2.78257083e-01,  5.49227425e+00, -2.79380559e-01,
        -2.76